### PR TITLE
css-canvas-medical - brighitte johnson

### PR DESCRIPTION
**Pull request by brij8**
i'm stuck on getting the hero.jpg to match the size and overlay(?) effect of the the original, and i didn't build out all the buttons/links... and i'm sure the code could be organized better...
but i want to move on to the next thing. let me know what you think i should fix and i will make those changes. 👍 
css-canvas-medical

### CODE REVIEW

**Comment by brij8** [comment]
got the hero.jpg looking better

css-canvas-medical-01

**Review by Zhiwutian — CHANGES_REQUESTED** [review]
Overall looks great! I would use the filter property to get the image to look correct: https://developer.mozilla.org/en-US/docs/Web/CSS/filter

Once that is completed, you are on done!

**Comment by brij8** [comment]
oo filter probably would have been easier.
i got the right results with an overlay, a negative margin on the image, and overflow: hidden on the container div.

**Review by Zhiwutian — APPROVED** [review]
👍🏼

**Pull request merged**
